### ISSUE TITLE
API doc

### ISSUE THREAD

**Issue by dlion** [jrowberg/bglib#27]
Hi, I need to create a simple application using BLE112.
I need to create a simple script that:
Discovery Mode -> Accept connection from another device -> Read a file and send datas read to a device which made a connection
I don't know where can I found the API doc to use your library.
I want to run this script on my raspberry pi, thanks for the help.

**Comment by jrowberg** [comment]
Hi @dlion,

The API Reference Guide from Bluegiga is under the User Guides section of the Bluegiga product pages for devices that support BGAPI.

https://www.bluegiga.com/en-US/products/bled112-bluetooth-smart-dongle/#documentation

I also recommend reading through the Bluetooth Smart Knowledge Base articles:

https://bluegiga.zendesk.com/forums/21316731-Bluetooth-Smart

If you have support questions, refer to the Community Forum (now Silabs.com since they bought Bluegiga):

http://community.silabs.com/t5/Wireless/bd-p/4
