### ISSUE TITLE
Creating multiple connections

### ISSUE THREAD

**Issue by nalauder** [jrowberg/bglib#30]
Using this library i have been able to only connect to one module to my dongle. Whenever i try to connect a second, it interferes with the incoming data checking from the first dongle. Is it possible to support more than one connection with this library. If so, how?

**Comment by jrowberg** [comment]
The library itself is agnostic when it comes to multiple connections. It simply provides an access layer to the binary protocol underneath. In order to support multiple connections, you must have the module/dongle configured correctly as described in the Bluetooth Smart Module Configuration Guide. Specifically, you need the <connections> tag in the optional "config.xml" file compiled with a connection count limit. See the following support forum thread:

http://community.silabs.com/t5/Bluetooth-Wi-Fi/Multiple-connections-bonding-limitation/td-p/148840

It is also critical to make sure you pay attention to the connection handle that is present in all GATT client API methods and in the `connection_status` event that occurs when the connection is established. The API always gives you enough information to differentiate between data belonging to each slave.

**Comment by nalauder** [comment]
Working with multiple connection now

**Comment by sd1026** [comment]
I need to connect 5 ble devices with bled112 dongle, and they all have common characteristics, and i want to subscribe to only of them in each one at the same time. How do i do it.
Now, it only picks up the latest connection or the first one and gives notifications, this is not what i want. I want simultaneous data from all slaves. Is there any approach to do it.

This is my code:
`import logging
import pygatt
from binascii import hexlify
import time
import asyncio
from functools import partial
import atexit
import struct
from pygatt.exceptions import NotConnectedError, NotificationTimeout

adapter = pygatt.BGAPIBackend()

CHAR_UUID = "00000080-0001-11e1-ac36-0002a5d5c51b"

msg = ""
qx, qy, qz, qw = "", "", "", ""
addresses_clear = []
adapters = []
# List of devices.
devices = []

# def exit():
#     print("Utility ending")
#     adapter.stop()
#     for address in addresses_clear:
#         adapter.clear_bond(address)
#     devices.clear()
# atexit.register(exit)

def handle_data(address, handle, value):
    hex_string = value.hex()
    print(f"Received data: {address} %s" % hexlify(value))
    # msg = ("".join(reversed([hex_string[i:i + 2] for i in range(0, len(hex_string), 2)])))
    #
    # qw = msg[4:12]
    # new_qw = str(round(struct.unpack('!f', bytes.fromhex(qw))[0], 5))
    #
    # qz = msg[12:20]
    # new_qz = str(round(struct.unpack('!f', bytes.fromhex(qz))[0], 5))
    #
    # qy = msg[20:28]
    # new_qy = str(round(struct.unpack('!f', bytes.fromhex(qy))[0], 5))
    #
    # qx = msg[28:36]
    # new_qx = str(round(struct.unpack('!f', bytes.fromhex(qx))[0], 5))
    #
    # new_string = address + " " + new_qx + " " + new_qy + " " + new_qz + " " + new_qw + " "
    # print(new_string)

def run(addresses):
    loop = asyncio.get_event_loop()

    tasks = asyncio.gather(*(connect_to_device(address) for address in addresses))

    loop.run_until_complete(tasks)

async def connect_to_device(address):

    try:
        device = adapter.connect(address, interval_min=32, interval_max=48, latency=0)
        devices.append(device)
        print(f"connected: {address}")
    except Exception as e:
        print(f"Exception: {e}")
        # try:
        #     device = adapter.connect(address, interval_min=10, interval_max=30, supervision_timeout=900)
        #     device.subscribe("00000080-0001-11e1-ac36-0002a5d5c51b", callback=partial(handle_data, address))
        # except NotConnectedError:
        #     print(f"Not connected error: ", NotConnectedError)

if __name__ == "__main__":
    adapter.start()
    logging.basicConfig(filename="sensors_7.log", level=logging.INFO)
    logging.info("Started")
    run(["26:80:E1:C1:11:D0", "26:80:E1:C1:90:51", "26:80:E1:4E:F8:B6", "26:80:E1:AD:99:34", "26:80:E1:16:E4:F2"])`
